UPDATE permissions
SET name = CASE UPPER(name)
    WHEN 'ANALYTICS_READ' THEN 'READ_ANALYTICS'
    WHEN 'CATEGORY_CREATE' THEN 'CREATE_CATEGORY'
    WHEN 'CATEGORY_DELETE' THEN 'DELETE_CATEGORY'
    WHEN 'CATEGORY_READ' THEN 'READ_CATEGORY'
    WHEN 'CATEGORY_UPDATE' THEN 'UPDATE_CATEGORY'
    WHEN 'INVENTORY_IMPORT' THEN 'IMPORT_INVENTORY'
    WHEN 'INVENTORY_READ' THEN 'READ_INVENTORY'
    WHEN 'ORDER_CONFIRM' THEN 'CONFIRM_ORDER'
    WHEN 'ORDER_READ' THEN 'READ_ORDER'
    WHEN 'ORDER_SHIP' THEN 'SHIP_ORDER'
    WHEN 'PAYMENT_READ' THEN 'READ_PAYMENT'
    WHEN 'PRODUCT_CREATE' THEN 'CREATE_PRODUCT'
    WHEN 'PRODUCT_DELETE' THEN 'DELETE_PRODUCT'
    WHEN 'PRODUCT_IMAGE_UPLOAD' THEN 'UPLOAD_PRODUCT_IMAGE'
    WHEN 'PRODUCT_READ' THEN 'READ_PRODUCT'
    WHEN 'PRODUCT_UPDATE' THEN 'UPDATE_PRODUCT'
    WHEN 'RBAC_MANAGE' THEN 'MANAGE_RBAC'
    WHEN 'RBAC_READ' THEN 'READ_RBAC'
    WHEN 'USER_CREATE' THEN 'CREATE_USER'
    WHEN 'USER_PASSWORD_RESET' THEN 'RESET_USER_PASSWORD'
    WHEN 'USER_READ' THEN 'READ_USER'
    WHEN 'USER_ROLE_ASSIGN' THEN 'ASSIGN_USER_ROLE'
    WHEN 'USER_STATUS_UPDATE' THEN 'UPDATE_USER_STATUS'
    WHEN 'USER_UPDATE' THEN 'UPDATE_USER'
    WHEN 'CUSTOMER_APP_ACCESS' THEN 'ACCESS_CUSTOMER_APP'
    WHEN 'CUSTOMER_ADDRESS_MANAGE' THEN 'MANAGE_CUSTOMER_ADDRESS'
    WHEN 'CUSTOMER_ADDRESS_READ' THEN 'READ_CUSTOMER_ADDRESS'
    WHEN 'CUSTOMER_CART_MANAGE' THEN 'MANAGE_CUSTOMER_CART'
    WHEN 'CUSTOMER_CHAT_MANAGE' THEN 'MANAGE_CUSTOMER_CHAT'
    WHEN 'CUSTOMER_CHECKOUT_MANAGE' THEN 'MANAGE_CUSTOMER_CHECKOUT'
    WHEN 'CUSTOMER_HEALTH_PROFILE_READ' THEN 'READ_CUSTOMER_HEALTH_PROFILE'
    WHEN 'CUSTOMER_HEALTH_PROFILE_UPDATE' THEN 'UPDATE_CUSTOMER_HEALTH_PROFILE'
    WHEN 'CUSTOMER_ORDER_CANCEL' THEN 'CANCEL_CUSTOMER_ORDER'
    WHEN 'CUSTOMER_ORDER_READ' THEN 'READ_CUSTOMER_ORDER'
    WHEN 'CUSTOMER_PROFILE_READ' THEN 'READ_CUSTOMER_PROFILE'
    WHEN 'CUSTOMER_PROFILE_UPDATE' THEN 'UPDATE_CUSTOMER_PROFILE'
    WHEN 'CUSTOMER_PRESCRIPTION_READ' THEN 'READ_CUSTOMER_PRESCRIPTION'
    WHEN 'CUSTOMER_REVIEW_MANAGE' THEN 'MANAGE_CUSTOMER_REVIEW'
    WHEN 'PHARMACIST_APP_ACCESS' THEN 'ACCESS_PHARMACIST_APP'
    WHEN 'PHARMACIST_CHAT_MANAGE' THEN 'MANAGE_PHARMACIST_CHAT'
    WHEN 'PHARMACIST_CONSULTATION_READ' THEN 'READ_PHARMACIST_CONSULTATION'
    WHEN 'PHARMACIST_PATIENT_HISTORY_READ' THEN 'READ_PHARMACIST_PATIENT_HISTORY'
    WHEN 'PHARMACIST_PROFILE_READ' THEN 'READ_PHARMACIST_PROFILE'
    WHEN 'PHARMACIST_PROFILE_UPDATE' THEN 'UPDATE_PHARMACIST_PROFILE'
    WHEN 'PHARMACIST_PRESCRIPTION_MANAGE' THEN 'MANAGE_PHARMACIST_PRESCRIPTION'
    ELSE name
END,
updated_at = NOW()
WHERE UPPER(name) IN (
    'ANALYTICS_READ',
    'CATEGORY_CREATE',
    'CATEGORY_DELETE',
    'CATEGORY_READ',
    'CATEGORY_UPDATE',
    'INVENTORY_IMPORT',
    'INVENTORY_READ',
    'ORDER_CONFIRM',
    'ORDER_READ',
    'ORDER_SHIP',
    'PAYMENT_READ',
    'PRODUCT_CREATE',
    'PRODUCT_DELETE',
    'PRODUCT_IMAGE_UPLOAD',
    'PRODUCT_READ',
    'PRODUCT_UPDATE',
    'RBAC_MANAGE',
    'RBAC_READ',
    'USER_CREATE',
    'USER_PASSWORD_RESET',
    'USER_READ',
    'USER_ROLE_ASSIGN',
    'USER_STATUS_UPDATE',
    'USER_UPDATE',
    'CUSTOMER_APP_ACCESS',
    'CUSTOMER_ADDRESS_MANAGE',
    'CUSTOMER_ADDRESS_READ',
    'CUSTOMER_CART_MANAGE',
    'CUSTOMER_CHAT_MANAGE',
    'CUSTOMER_CHECKOUT_MANAGE',
    'CUSTOMER_HEALTH_PROFILE_READ',
    'CUSTOMER_HEALTH_PROFILE_UPDATE',
    'CUSTOMER_ORDER_CANCEL',
    'CUSTOMER_ORDER_READ',
    'CUSTOMER_PROFILE_READ',
    'CUSTOMER_PROFILE_UPDATE',
    'CUSTOMER_PRESCRIPTION_READ',
    'CUSTOMER_REVIEW_MANAGE',
    'PHARMACIST_APP_ACCESS',
    'PHARMACIST_CHAT_MANAGE',
    'PHARMACIST_CONSULTATION_READ',
    'PHARMACIST_PATIENT_HISTORY_READ',
    'PHARMACIST_PROFILE_READ',
    'PHARMACIST_PROFILE_UPDATE',
    'PHARMACIST_PRESCRIPTION_MANAGE'
);
