DELETE FROM role_permissions
WHERE permission_id IN (
    SELECT id
    FROM permissions
    WHERE name IN (
        'ACCESS_CUSTOMER_APP',
        'MANAGE_CUSTOMER_ADDRESS',
        'READ_CUSTOMER_ADDRESS',
        'MANAGE_CUSTOMER_CART',
        'MANAGE_CUSTOMER_CHAT',
        'MANAGE_CUSTOMER_CHECKOUT',
        'READ_CUSTOMER_HEALTH_PROFILE',
        'UPDATE_CUSTOMER_HEALTH_PROFILE',
        'CANCEL_CUSTOMER_ORDER',
        'READ_CUSTOMER_ORDER',
        'READ_CUSTOMER_PROFILE',
        'UPDATE_CUSTOMER_PROFILE',
        'READ_CUSTOMER_PRESCRIPTION',
        'MANAGE_CUSTOMER_REVIEW',
        'ACCESS_PHARMACIST_APP',
        'MANAGE_PHARMACIST_CHAT',
        'READ_PHARMACIST_CONSULTATION',
        'READ_PHARMACIST_PATIENT_HISTORY',
        'READ_PHARMACIST_PROFILE',
        'UPDATE_PHARMACIST_PROFILE',
        'MANAGE_PHARMACIST_PRESCRIPTION'
    )
       OR role_type IN ('CUSTOMER', 'PHARMACIST')
);

DELETE FROM permissions
WHERE name IN (
    'ACCESS_CUSTOMER_APP',
    'MANAGE_CUSTOMER_ADDRESS',
    'READ_CUSTOMER_ADDRESS',
    'MANAGE_CUSTOMER_CART',
    'MANAGE_CUSTOMER_CHAT',
    'MANAGE_CUSTOMER_CHECKOUT',
    'READ_CUSTOMER_HEALTH_PROFILE',
    'UPDATE_CUSTOMER_HEALTH_PROFILE',
    'CANCEL_CUSTOMER_ORDER',
    'READ_CUSTOMER_ORDER',
    'READ_CUSTOMER_PROFILE',
    'UPDATE_CUSTOMER_PROFILE',
    'READ_CUSTOMER_PRESCRIPTION',
    'MANAGE_CUSTOMER_REVIEW',
    'ACCESS_PHARMACIST_APP',
    'MANAGE_PHARMACIST_CHAT',
    'READ_PHARMACIST_CONSULTATION',
    'READ_PHARMACIST_PATIENT_HISTORY',
    'READ_PHARMACIST_PROFILE',
    'UPDATE_PHARMACIST_PROFILE',
    'MANAGE_PHARMACIST_PRESCRIPTION'
)
   OR role_type IN ('CUSTOMER', 'PHARMACIST');
